#!/bin/sh
set -e
# Automatically added by dh_installsystemd/12ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'connman-wait-online.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/12ubuntu1
if [ -x "/etc/init.d/connman" ] && [ "$1" = remove ]; then
	invoke-rc.d connman stop || exit 1
fi
# End automatically added section
