#!/bin/sh
set -e
# Automatically added by dh_installinit/12ubuntu1
if [ -x "/etc/init.d/cpufrequtils" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native cpufrequtils stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installinit/12ubuntu1
if [ -x "/etc/init.d/loadcpufreq" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native loadcpufreq stop || exit 1
fi
# End automatically added section
