#!/bin/sh
set -e

case "$1" in
    configure)
        # Update grub
        if [ -e /boot/grub/grub.cfg ] && [ -x "$(which update-grub)" ]; then
            update-grub
        fi
    ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/friendly-recovery" ]; then
		update-rc.d friendly-recovery defaults >/dev/null || exit $?
	fi
fi
# End automatically added section


exit 0
