#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/gnome-flashback-screensaver.desktop 3.18.2-1~ gnome-flashback-common -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/gnome-flashback-nm-applet.desktop 3.18.2-1~ gnome-flashback-common -- "$@"
# End automatically added section
