#!/bin/sh
set -e
# Automatically added by dh_installsystemd/12.9ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'dundee.service' 'ofono.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/12.9ubuntu1
dpkg-maintscript-helper rm_conffile /etc/init/ofono.conf 1.31-2ubuntu1\~ -- "$@"
# End automatically added section
