#!/bin/sh
set -e
# Automatically added by dh_installsystemd/12.7ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'rsync.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/12.7ubuntu1
if [ -x "/etc/init.d/rsync" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native rsync stop || exit 1
fi
# End automatically added section
