#!/bin/sh

set -e

case "$1" in 
  remove|purge)
	if [ -L /etc/X11/app-defaults/XScreenSaver ]; then
	    if [ "$(readlink /etc/X11/app-defaults/XScreenSaver)" = "XScreenSaver-nogl" -o \
	         "$(readlink /etc/X11/app-defaults/XScreenSaver)" = "XScreenSaver-gl" ]; then
		rm /etc/X11/app-defaults/XScreenSaver
	    fi
	fi
	;;
esac

# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section

