#!/bin/sh

set -e

# Use the correct app defaults
cd /etc/X11/app-defaults
if [ ! -e XScreenSaver ]; then
    if [ -f XScreenSaver-gl ]; then
	ln -sf XScreenSaver-gl  XScreenSaver
    else
	ln -sf XScreenSaver-nogl XScreenSaver
    fi
fi

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section

