#!/bin/sh -e
# initramfs hook for fixing broken rtc clock
# without battery

PREREQ="udev"

# Output pre-requisites
prereqs()
{
        echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

# We use the full dumpe2fs because we basically get it for "free"
# if we're already on extN due to e2fsck pulling in all the libs:
copy_exec /sbin/dumpe2fs /sbin
